In [1]:
import os
import django
import numpy as np

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'demo.settings')
# 防止 SynchronousOnlyOperation 错误
# You cannot call this from an async context
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
django.setup()

In [2]:
from similarity2.algorithm import cosine_similarity
from similarity2.globals import MODEL

model = MODEL

D:\jetbrains projects\pycharm\venv\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
D:\jetbrains projects\pycharm\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\jetbrains projects\pycharm\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\jetbrains 

INFO:tensorflow:Using config: {'_model_dir': 'D:\\jetbrains projects\\pycharm\\Similarity\\similarity\\model/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.8
  allow_growth: true
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000020983F2EEB8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
正在使用CPU


In [5]:
import torch
li = [
    ("中国","日本"),
    ("中国","韩国"),
    ("中国","英国"),
    ("中国","美国"),
    ("政府","政府"),
]

for a,b in li:
    print(a,b)
    a:torch.Tensor = torch.Tensor(model[a]).unsqueeze(0)
    b:torch.Tensor = torch.Tensor(model[b]).unsqueeze(0)
    print(cosine_similarity(a, b))

中国 日本
tensor([[0.8466]])
中国 韩国
tensor([[0.8039]])
中国 英国
tensor([[0.7100]])
中国 美国
tensor([[0.8164]])
政府 政府
tensor([[1.0000]])


In [16]:
li = model.most_similar(positive=["国王","女性"],negative=["男性"])
for item in li:
    print(item,model.key_to_index[item[0]])

('女皇', 0.7742870450019836) 8036
('王后', 0.7482188940048218) 9912
('国君', 0.720130443572998) 18652
('大祭司', 0.716486394405365) 13913
('教宗', 0.713326632976532) 35802
('教皇', 0.7109844088554382) 8609
('女王', 0.7061516642570496) 4155
('王储', 0.705417275428772) 45654
('国主', 0.7028873562812805) 38580
('皇帝', 0.6982800960540771) 714
